### ISSUE TITLE
pulpcore.plugin.tasking.add_and_remove causing repos to break

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulpcore#2465]
**Version**
Checked out at commit 8a8ef9ab11a3e825099fdd27855557f1e806428e
```
{
    "versions": [
        {
            "component": "core",
            "version": "3.18.2.dev"
        },
        {
            "component": "ansible",
            "version": "0.13.0.dev"
        },
        {
            "component": "container",
            "version": "2.10.3.dev"
        }
    ],
```

**Describe the bug**
In some cases the `add_and_remove` function can cause repositories to break.

**To Reproduce**
I've only been able to reproduce this problem via the tests for pulp ansible.

1. Check out pulp ansible here: https://github.com/newswangerd/pulp_ansible/tree/debugging/weird-add-and-remove-count-issue
2. Install the pulp ansible bindings
3. Run the collection deletion functional tests with `pytest -v -r sx --color=yes --pyargs pulp_ansible.tests.functional.api.collection.v3.test_deletion`
4. The tests fail when `monitor_task` tries to poll the collection deletion task

The tests fail with the following stack trace:

```
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]: pulp [c84f467eaa3348aea771e9138b7de735]: django.request:ERROR: Internal Server Error: /pulp/api/v3/tasks/d4921162-cf00-4f81-83d6-6f9b453c419b/
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]: Traceback (most recent call last):
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     response = get_response(request)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     return view_func(*args, **kwargs)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     return self.dispatch(request, *args, **kwargs)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     response = self.handle_exception(exc)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     self.raise_uncaught_exception(exc)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     raise exc
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     response = handler(request, *args, **kwargs)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/mixins.py", line 56, in retrieve
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     return Response(serializer.data)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     ret = super().data
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     self._data = self.to_representation(self.instance)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     ret[field.field_name] = field.to_representation(attribute)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/relations.py", line 542, in to_representation
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     return [
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/relations.py", line 543, in <listcomp>
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     self.child_relation.to_representation(value)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/home/vagrant/devel/pulpcore/pulpcore/app/serializers/base.py", line 318, in to_representation
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     return serializer.data.get("pulp_href")
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     ret = super().data
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     self._data = self.to_representation(self.instance)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     ret[field.field_name] = field.to_representation(attribute)
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/home/vagrant/devel/pulpcore/pulpcore/app/serializers/repository.py", line 371, in to_representation
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     item_dict = {"count": count_detail.count, "href": count_detail.content_href}
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:   File "/home/vagrant/devel/pulpcore/pulpcore/app/models/repository.py", line 1118, in content_href
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]:     ctype_model = ctype_query.first().cast().__class__
Mar 31 12:09:40 hub.dnewswan-mac.example.com gunicorn[14388]: AttributeError: 'NoneType' object has no attribute 'cast'

```

Navigating to the `/pulp/api/v3/tasks/`, the task detail endpoint for the deletion task as well as the latest version of the repo that's being updated  fail with the same error.

The root cause seems to be that `_compute_counts()` isn't getting called on the repo when it's updated, which causes the repository serializer to break when getting the href for created resources on the task API as well as on the api for the latest repository version. 

**Expected behavior**
The repository version and task endpoints shouldn't break when I call the delete API in pulp_ansible. 

**Additional context**
None

**Comment by mdellweg** [comment]
Interestingly enough, i get a slightly different trace:

```
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]: Traceback (most recent call last):
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     response = get_response(request)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     return view_func(*args, **kwargs)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     return self.dispatch(request, *args, **kwargs)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     response = self.handle_exception(exc)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     self.raise_uncaught_exception(exc)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     raise exc
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     response = handler(request, *args, **kwargs)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/mixins.py", line 56, in retrieve
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     return Response(serializer.data)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     ret = super().data
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     self._data = self.to_representation(self.instance)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     ret[field.field_name] = field.to_representation(attribute)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/relations.py", line 542, in to_representation
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     return [
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/relations.py", line 543, in <listcomp>
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     self.child_relation.to_representation(value)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/home/vagrant/devel/pulpcore/pulpcore/app/serializers/base.py", line 318, in to_representation
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     return serializer.data.get("pulp_href")
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     ret = super().data
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     self._data = self.to_representation(self.instance)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/usr/local/lib/pulp/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     ret[field.field_name] = field.to_representation(attribute)
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/home/vagrant/devel/pulpcore/pulpcore/app/serializers/repository.py", line 371, in to_representation
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     item_dict = {"count": count_detail.count, "href": count_detail.content_href}
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/home/vagrant/devel/pulpcore/pulpcore/app/models/repository.py", line 1115, in content_href
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     ctype_view = get_view_name_for_model(ctype_model, "list")
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:   File "/home/vagrant/devel/pulpcore/pulpcore/app/util.py", line 78, in get_view_name_for_model
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]:     raise LookupError("view not found")
Apr 01 10:10:34 pulp3-source-debian11 gunicorn[2966]: LookupError: view not found
```

**Comment by mdellweg** [comment]
I believe i could identify a subsequent delete call that cascade deleted content to be the root cause for these errors.
I will close as not-a-bug.

**Comment by dralley** [comment]
@newswangerd @mdellweg I'm pretty sure this is https://github.com/pulp/pulpcore/issues/2085

**Comment by mdellweg** [comment]
> @newswangerd @mdellweg I'm pretty sure this is #2085

I could trace this down to rogue content deletion (not through orphan_cleanup) that was still in repo versions. To e this is not a bug in pulpcore.

**Comment by dralley** [comment]
Reopened: A new user has encountered this with orphan cleanup while using the RPM plugin.  Same traceback.

https://community.theforeman.org/t/delete-orphaned-content-task-failing-server-error-500/30401

**Comment by dralley** [comment]
Never mind, mixed this up with the orphan cleanup issue, got confused by my own comment
