### ISSUE TITLE
Database connection already closed

### ISSUE THREAD

**Issue by honzasara** [pulp/pulpcore#2744]
Hello, Im newbie here,

**Version**
Installed via pulp-operator
Version:
  pulp-core: 3.19.0
  pulp-deb: 2.18.0

**Describe the bug**
I have a problem with communication the database. Is running long Debian mirror sync, about one hour. After this time is problem. `django.db.utils.InterfaceError: connection already closed`

My settings.py:
```
CACHE_ENABLED = True
DB_ENCRYPTION_KEY = "/etc/pulp/keys/database_fields.symmetric.key"
GALAXY_COLLECTION_SIGNING_SERVICE = "ansible-default"
ANSIBLE_CERTS_DIR = "/etc/pulp/keys/"
DATABASES = {"default": {"HOST": "repo-db", "ENGINE": "django.db.backends.postgresql_psycopg2", "NAME": "pulp", "USER": "pulp", "PASSWORD": "xxxxx", "PORT": "7432", "CONN_MAX_AGE": 0, "OPTIONS": {"sslmode": "disable"}} }
REDIS_HOST = "pulp-redis-svc"
REDIS_PORT = 6379
REDIS_PASSWORD = ""
CONTENT_ORIGIN =       "http://pulp-staging"
ANSIBLE_API_HOSTNAME = "http://pulp-staging"
X_PULP_CONTENT_HOST = "pulp-content-svc"
X_PULP_CONTENT_PORT = "24816"
DEBUG = True

REDIRECT_TO_OBJECT_STORAGE = False

AWS_ACCESS_KEY_ID = 'xxx
AWS_SECRET_ACCESS_KEY = 'xx'
AWS_STORAGE_BUCKET_NAME = 'pulp3'
AWS_DEFAULT_ACL = 'public-read'
AWS_AUTO_CREATE_BUCKET = True
S3_USE_SIGV4 = True
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"
#AWS_S3_REGION_NAME = "eu-central-1"
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_ROOT = ''
AWS_S3_ENDPOINT_URL = "https://ceph-radosgw"
AWS_S3_VERIFY = False

FORBIDDEN_CHECKSUM_WARNINGS = False

TOKEN_SERVER = "xxxxccccvvvvbbbb"

LOGGING = {"dynaconf_merge": True,"loggers": {'': {'handlers': ['console'],'level': 'DEBUG',}}}
```

**To Reproduce**
```
1. http $PULP_AUTH patch $PULP_HOST/pulp/api/v3/remotes/deb/apt/6e818833-03e7-42dc-8869-f1d1f6e0f2af/ name="bionic" url="https://cz.archive.ubuntu.com/ubuntu/" components=" main" distributions="bionic" architectures="amd64"

2. http $PULP_AUTH post $PULP_HOST/pulp/api/v3/repositories/deb/apt/fad622c5-eb71-4916-8e43-6e379711622b/sync/ remote=/pulp/api/v3/remotes/deb/apt/6e818833-03e7-42dc-8869-f1d1f6e0f2af/
```

**Additional context**

log from Tasks:

```
http  $PULP_AUTH get $PULP_HOST/pulp/api/v3/tasks/648821ff-a2d6-46f0-a9a2-7c350df79e6e/
HTTP/1.1 200 OK
access-control-expose-headers: Correlation-ID
allow: GET, PATCH, DELETE, HEAD, OPTIONS
content-length: 1242
content-type: application/json
correlation-id: 7649b9f4285c412bbdfc3f0abe1b8e5c
date: Wed, 18 May 2022 04:23:53 GMT
referrer-policy: same-origin
server: envoy
vary: Accept, Cookie
x-content-type-options: nosniff
x-envoy-upstream-service-time: 759
x-frame-options: DENY

{
    "child_tasks": [],
    "created_resources": [],
    "error": {
        "reason": "Task process died unexpectedly with exitcode 1."
    },
    "finished_at": "2022-05-17T22:45:51.476959Z",
    "logging_cid": "6ec60aad7ca34e218ef36035b3e77361",
    "name": "pulp_deb.app.tasks.synchronizing.synchronize",
    "parent_task": null,
    "progress_reports": [
        {
            "code": "associating.content",
            "done": 121739,
            "message": "Associating Content",
            "state": "completed",
            "suffix": null,
            "total": null
        },
        {
            "code": "update.release_file",
            "done": 1,
            "message": "Update ReleaseFile units",
            "state": "completed",
            "suffix": null,
            "total": null
        },
        {
            "code": "update.packageindex",
            "done": 1,
            "message": "Update PackageIndex units",
            "state": "completed",
            "suffix": null,
            "total": null
        },
        {
            "code": "sync.downloading.artifacts",
            "done": 6,
            "message": "Downloading Artifacts",
            "state": "completed",
            "suffix": null,
            "total": null
        }
    ],
    "pulp_created": "2022-05-17T19:00:16.907742Z",
    "pulp_href": "/pulp/api/v3/tasks/648821ff-a2d6-46f0-a9a2-7c350df79e6e/",
    "reserved_resources_record": [
        "/pulp/api/v3/repositories/deb/apt/fad622c5-eb71-4916-8e43-6e379711622b/",
        "shared:/pulp/api/v3/remotes/deb/apt/6e818833-03e7-42dc-8869-f1d1f6e0f2af/"
    ],
    "started_at": "2022-05-17T19:00:16.972740Z",
    "state": "failed",
    "task_group": null,
    "worker": "/pulp/api/v3/workers/58539fd5-9698-4c77-a597-324a589a7236/"
}
```

log from pulp-worker:

```
pulp [6ec60aad7ca34e218ef36035b3e77361]: pulpcore.plugin.stages.api:DEBUG: [140600576084432] EndStage - next: PackageReleaseComponent.
pulp [6ec60aad7ca34e218ef36035b3e77361]: pulpcore.plugin.stages.api:DEBUG: [140600576084480] ContentAssociation - put: PackageReleaseComponent
pulp [6ec60aad7ca34e218ef36035b3e77361]: pulpcore.plugin.stages.api:DEBUG: [140600576084432] EndStage - next: PackageReleaseComponent.
pulp [6ec60aad7ca34e218ef36035b3e77361]: pulpcore.plugin.stages.api:DEBUG: [140600576084480] ContentAssociation - shutdown.
pulp [6ec60aad7ca34e218ef36035b3e77361]: pulpcore.plugin.stages.api:DEBUG: [140600576084480] ContentAssociation - put end-marker.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/models/repository.py", line 1044, in __exit__
    repository.finalize_new_version(self)
  File "/usr/local/lib/python3.9/site-packages/pulp_deb/app/models/repository.py", line 67, in finalize_new_version
    remove_duplicates(new_version)
  File "/usr/local/lib/python3.9/site-packages/pulpcore/plugin/repo_version_utils.py", line 43, in remove_duplicates
    existing_content = repository_version.previous().content
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/models/repository.py", line 891, in previous
    self.repository.versions.complete()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 317, in __getitem__
    qs._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 277, in _set_autocommit
    self.connection.autocommit = autocommit
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pulpcore/tasking/pulpcore_worker.py", line 445, in _perform_task
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pulp_deb/app/tasks/synchronizing.py", line 161, in synchronize
    DebDeclarativeVersion(first_stage, repository, mirror=mirror).create()
  File "/usr/local/lib/python3.9/site-packages/pulpcore/plugin/stages/declarative_version.py", line 161, in create
    loop.run_until_complete(pipeline)
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/models/repository.py", line 1071, in __exit__
    self.delete()
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/models/repository.py", line 985, in delete
    with transaction.atomic():
  File "/usr/local/lib/python3.9/site-packages/django/db/transaction.py", line 207, in __enter__
    connection.set_autocommit(False, force_begin_transaction_with_broken_autocommit=True)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 415, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 277, in _set_autocommit
    self.connection.autocommit = autocommit
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 277, in _set_autocommit
    self.connection.autocommit = autocommit
django.db.utils.InterfaceError: connection already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 236, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/pulpcore/tasking/pulpcore_worker.py", line 453, in _perform_task
    task.set_failed(exc, tb)
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/models/task.py", line 278, in set_failed
    Task.objects.filter(pk=self.pk)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 783, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 236, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
pulp [None]: pulpcore.tasking.pulpcore_worker:WARNING: Task process for 648821ff-a2d6-46f0-a9a2-7c350df79e6e exited with non zero exitcode 1.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Cleaning up task 648821ff-a2d6-46f0-a9a2-7c350df79e6e and marking as failed. Reason: Task process died unexpectedly with exitcode 1.
pulp [None]: pulpcore.tasking.pulpcore_worker:DEBUG: Worker 13@pulp-worker-784c65dc9b-6htcv entering sleep state.
pulp [None]: pulpcore.tasking.pulpcore_worker:DEBUG: Worker 13@pulp-worker-784c65dc9b-6htcv received wakeup call.
pulp [None]: pulpcore.tasking.pulpcore_worker:DEBUG: Worker 13@pulp-worker-784c65dc9b-6htcv received wakeup call.
pulp [None]: pulpcore.tasking.pulpcore_worker:DEBUG: Worker 13@pulp-worker-784c65dc9b-6htcv entering sleep state.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker '13@pulp-worker-784c65dc9b-6htcv' is back online.
```

Thans you for tip how to fix this problem

**Comment by fao89** [comment]
maybe you need to bump the memory limit:
```yaml
worker:
  replicas: 2
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 8Gi
```      
https://github.com/pulp/pulp-operator/commit/f4093d21e359d13b5fe6734b4114be4a75eed207

**Comment by dkliban** [comment]
This seems like a configuration problem.
