### ISSUE TITLE
Telemetry of dev installs submitted to production site (https://anaytics.pulpproject.org/)

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#3213]
**Version**
3.20.z and 3.21.z

**Describe the bug**
Telemetry of a non-GA component is being submitted to analytics.pulpproject.org. This is unexpected and causes summarization to stop working with this exception:

```
Traceback (most recent call last):
  File "/srv/app/./manage.py", line 22, in <module>
    main()
  File "/srv/app/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/srv/app/pulpanalytics/management/commands/summarize.py", line 112, in handle
    self._handle_components(systems, summary)
  File "/srv/app/pulpanalytics/management/commands/summarize.py", line 74, in _handle_components
    semver_version = semver.parse(component.version)
  File "/opt/app-root/lib64/python3.9/site-packages/semver.py", line 159, in wrapper
    return func(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/semver.py", line 190, in parse
    return VersionInfo.parse(version).to_dict()
  File "/opt/app-root/lib64/python3.9/site-packages/semver.py", line 726, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: 2.0.0a6 is not valid SemVer string
```

**Comment by bmbouter** [comment]
@pulp/core I added prio-list to this for two reasons. Please let me know if you'd like me to do something differently.

* The production telemetry site is incorrectly receiving data from developer installations, which is a significant data quality problem.
* There are no other unassigned issues with prio-list.

**Comment by bmbouter** [comment]
This is to handle plugins with pre-release names that don't end in `.dev`, e.g. `pulp-ostree 2.0.0a6`.
