### ISSUE TITLE
dynaconf/click "env file" error

### ISSUE THREAD

**Issue by mikedep333** [pulp/pulpcore#3310]
During s6 container startup, this error is always outputted. It seems harmless, but it is cluttering up logs (e.g., in CI):

```
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/settings.py", line 296, in <module>
    from dynaconf import DjangoDynaconf, Validator  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/__init__.py", line 1, in <module>
    from dynaconf.base import LazySettings  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/base.py", line 15, in <module>
    from dynaconf.loaders import env_loader
  File "/usr/local/lib/python3.8/site-packages/dynaconf/loaders/env_loader.py", line 6, in <module>
    from dynaconf.vendor.dotenv import cli as dotenv_cli
  File "/usr/local/lib/python3.8/site-packages/dynaconf/vendor/dotenv/cli.py", line 16, in <module>
    @click.option('-f','--file',default=os.path.join(os.getcwd(),'.env'),type=click.Path(exists=_A),help='Location of the .env file, defaults to .env file in current working directory.')
FileNotFoundError: [Errno 2] No such file or directory
```

This started happening in September.

I tried downgrading dynaconf from 3.1.11 to 3.1.9, it did not help.
Click was last updated much earlier than september.

**Comment by decko** [comment]
I tried with the latest oci-env and pulp versions and the error message didn't show up. If @mikedep333 or someone else confirm it I would recommend close this issue.

Note: I had to remove all images and let oci-env to generate new ones to make it work properly.

**Comment by decko** [comment]
I left a draft PR waiting for the new release with this fix on it.
