### ISSUE TITLE
core.0054_add_public_key fails in kubenetes

### ISSUE THREAD

**Issue by amirrob** [pulp/pulpcore#3419]
**Version**
pulpcore                        3.21.0

**Describe the bug**
I have built an instance of pulp on podman without issue. Now I move to kuberntes I am getting a failure in core.0054_add_public_key...Operations. I can see table spaces veing created on postgres.

  Applying core.0053_remote_headers... OK
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/pulpcore/app/migrations/0054_add_public_key.py", line 60, in migrate_public_key_values
    gpg = gnupg.GPG()
  File "/usr/local/lib/python3.9/site-packages/gnupg.py", line 947, in __init__
    self._collect_output(p, result, stdin=p.stdin)
  File "/usr/local/lib/python3.9/site-packages/gnupg.py", line 1072, in _collect_output
    rr.start()
  File "/usr/lib64/python3.9/threading.py", line 892, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
+ /usr/local/bin/pulpcore-manager migrate auth --noinput
  Applying core.0054_add_public_key...Operations to perform:
  Apply all migrations: auth
Running migrations:

**To Reproduce**
Always when I migrate runs

**Expected behavior**
Core migrations to complete.

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by amirrob** [comment]
Some more details. These Images are built on RHEL 9 container. Have reverted to RHEL 8.
/usr/local/bin/pulpcore-manager migrate --noinput     is now able to complete and the environment is running

**Comment by dkliban** [comment]
Thanks for filing an issue. We are going to see if we can reproduce the problem on EL9.
