### ISSUE TITLE
An internal server error is raised when passing invalid data to the `modify` endpoint

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulpcore#3486]
When a user passes a dictionary to the `modify` endpoint, the validation and retrieval of a content unit fail.

```
pulp file remote create --name aaa --url https://fixtures.pulpproject.org/file/PULP_MANIFEST

export REPO_HREF=$(pulp file repository create --name aaa --remote aaa | jq -r ".pulp_href")
pulp file repository sync --name aaa

export CONTENT_ORIGIN=$(pulp status | jq -r ".content_settings.content_origin")

http ${CONTENT_ORIGIN}${REPO_HREF}modify/ remove_content_units:='[{"a": "b"}]' -v
```

```
pulp [ab2982a30380488c92b083f1bdc1ff8c]: django.request:ERROR: Internal Server Error: /pulp/api/v3/repositories/file/file/b3f5c77a-6ede-4de4-9ce9-c245ce0aae19/modify/
Traceback (most recent call last):
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/pulp/lib64/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs) 
  File "/home/vagrant/devel/pulpcore/pulpcore/plugin/actions.py", line 61, in modify
    remove_content_units[NamedModelViewSet.extract_pk(url)] = url
  File "/home/vagrant/devel/pulpcore/pulpcore/app/viewsets/base.py", line 219, in extract_pk
    match = resolve(urlparse(uri).path)
  File "/usr/lib64/python3.10/urllib/parse.py", line 392, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/lib64/python3.10/urllib/parse.py", line 128, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib64/python3.10/urllib/parse.py", line 112, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib64/python3.10/urllib/parse.py", line 112, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'dict' object has no attribute 'decode'
```

**Comment by lubosmj** [comment]
Closing in favour of https://github.com/pulp/pulpcore/issues/3326
