### ISSUE TITLE
Tracebacks in logs with quay.io/pulp/pulp 

### ISSUE THREAD

**Issue by praiskup** [pulp/pulpcore#3492]
**Version**

Seems like container: 8dc8e64d40a1f28ee03a5546882d49214592a2a50e40203d4b87f8346301f5dc

**Describe the bug**
Pulp doesn't seem to start correctly according to https://pulpproject.org/pulp-in-one-container/

**To Reproduce**
Follow the [steps](https://pulpproject.org/pulp-in-one-container/), the following fails:
```
$ podman exec -it pulp bash -c 'pulpcore-manager reset-admin-password'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/management/commands/reset-admin-password.py", line 35, in handle
    user = User.objects.get_or_create(username="admin", is_superuser=True, is_staff=True)[0]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^
```

**Additional context**

`podman logs pulp` are 4.2MB, large to upload.  The first traceback there is:
```
[oneshot] postgres-prepare: ^[[32mrunning Pulp migrations^[[0m
[oneshot] certs: ^[[32mfinished adding webserver certificate to the certificate store^[[0m
s6-rc: info: service certs successfully started
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/settings.py", line 393, in <module>
    with open(DB_ENCRYPTION_KEY, "rb") as key_file:
PermissionError: [Errno 13] Permission denied: '/etc/pulp/certs/database_fields.symmetric.key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/models/__init__.py", line 35, in <module>
    from .exporter import (  # noqa
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/models/exporter.py", line 11, in <module>
    from pulpcore.app.models.repository import Repository
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/models/repository.py", line 26, in <module>
    from pulpcore.cache import Cache
  File "/usr/local/lib/python3.8/site-packages/pulpcore/cache/__init__.py", line 1, in <module>
    from .cache import (  # noqa
  File "/usr/local/lib/python3.8/site-packages/pulpcore/cache/cache.py", line 16, in <module>
    from pulpcore.app.settings import settings
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/settings.py", line 396, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Could not load DB_ENCRYPTION_KEY file '/etc/pulp/certs/database_fields.symmetric.key': [Errno 13] Permission denied: '/etc/pulp/certs/database_fields.symmetric.key'

```

**Comment by ipanova** [comment]
What the podman version? where are you running it?
https://pulpproject.org/pulp-in-one-container/#podman-on-centos-7

**Comment by praiskup** [comment]
```
14:40:50 ~$ podman --version
podman version 4.3.1
14:40:53 ~$ rpm -q podman
podman-4.3.1-1.fc37.x86_64
```

**Comment by praiskup** [comment]
Also note that I'm not quite sure I'm using [the right image](https://github.com/pulp/pulpproject.org/pull/449).

**Comment by dkliban** [comment]
I tried to reproduce using the latest image from quay.io and I could not reproduce it. 

It seems like you have a permissions problem with the /etc/pulp/certs/ directory ... Here is what the permissions look like for me:
```
[dkliban@fedora ~]$ podman exec -it pulp bash
[root@25aedd4dc552 /]# ls -la /etc/pulp/
total 4
drwxr-xr-x. 1 root root  32 Jan  9 20:36 .
drwxr-xr-x. 1 root root   6 Dec 23 01:32 ..
drwxr-xr-x. 1 root root 248 Jan  9 20:36 certs
-rw-r--r--. 1 root root 162 Jan  9 20:35 settings.py
[root@25aedd4dc552 /]# ls -la /etc/pulp/certs/
total 24
drwxr-xr-x. 1 root root  248 Jan  9 20:36 .
drwxr-xr-x. 1 root root   32 Jan  9 20:36 ..
-rw-r-----. 1 root pulp   45 Jan  9 20:36 database_fields.symmetric.key
-rw-r--r--. 1 root pulp 1334 Jan  9 20:36 pulp_webserver.crt
-rw-r--r--. 1 root pulp 1175 Jan  9 20:36 pulp_webserver.csr
-rw-------. 1 root pulp 1675 Jan  9 20:36 pulp_webserver.key
-rw-------. 1 pulp pulp  227 Jan  9 20:36 token_private_key.pem
-rw-r--r--. 1 pulp pulp  178 Jan  9 20:36 token_public_key.pem
```

Can you share the output of the above commands for you?

**Comment by praiskup** [comment]
Looks promising, thanks!
```
[root@21e381ccf81f /]# ls -la /etc/pulp/
total 12
drwx------.  3 root root   80 Jan 10 09:19 .
drwxr-xr-x. 72 root root 4096 Dec 23 01:32 ..
drwxr-xr-x.  2 root root  160 Jan 10 09:19 certs
-rw-------.  1 root root  165 Jan 10 09:18 settings.py
```

**Comment by praiskup** [comment]
Indeed, I temporarily switched umask from 0077 to 0022, and recreated from scratch. That helped.

Could the permissions be fixed automatically?  I can see some tasks like:

    fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
    fix-attrs: warning: some fix files failed to apply

I'm actually in a user namespace;  so the files in /etc/pulp in container are owned by "fake root"
(== my non-privileged `praiskup` user).  We should have the rights to fix the permissions bits.

Nevertheless, it eventually worked!  Thank you.

For the sake of completeness, `podman logs pulp` shows:

```
Calling /etc/init/postgres-prepare
2023-01-10 09:29:25.952 UTC [12591] LOG:  redirecting log output to logging collector process
2023-01-10 09:29:25.952 UTC [12591] HINT:  Future log output will appear in directory "log".
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/settings.py", line 299, in <module>
    from dynaconf import DjangoDynaconf, Validator  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/__init__.py", line 3, in <module>
    from dynaconf.base import LazySettings  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/base.py", line 17, in <module>
    from dynaconf.loaders import env_loader
  File "/usr/local/lib/python3.8/site-packages/dynaconf/loaders/env_loader.py", line 8, in <module>
    from dynaconf.vendor.dotenv import cli as dotenv_cli
  File "/usr/local/lib/python3.8/site-packages/dynaconf/vendor/dotenv/cli.py", line 16, in <module>
    @click.option('-f','--file',default=os.path.join(os.getcwd(),'.env'),type=click.Path(exists=_A),help='Location of the .env file, defaults to .env file in current working directory.')
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/settings.py", line 299, in <module>
    from dynaconf import DjangoDynaconf, Validator  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/__init__.py", line 3, in <module>
    from dynaconf.base import LazySettings  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/base.py", line 17, in <module>
    from dynaconf.loaders import env_loader
  File "/usr/local/lib/python3.8/site-packages/dynaconf/loaders/env_loader.py", line 8, in <module>
    from dynaconf.vendor.dotenv import cli as dotenv_cli
  File "/usr/local/lib/python3.8/site-packages/dynaconf/vendor/dotenv/cli.py", line 16, in <module>
    @click.option('-f','--file',default=os.path.join(os.getcwd(),'.env'),type=click.Path(exists=_A),help='Location of the .env file, defaults to .env file in current working directory.')
FileNotFoundError: [Errno 2] No such file or directory
Database migrated!
ready
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/settings.py", line 299, in <module>
    from dynaconf import DjangoDynaconf, Validator  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/__init__.py", line 3, in <module>
    from dynaconf.base import LazySettings  # noqa
  File "/usr/local/lib/python3.8/site-packages/dynaconf/base.py", line 17, in <module>
    from dynaconf.loaders import env_loader
  File "/usr/local/lib/python3.8/site-packages/dynaconf/loaders/env_loader.py", line 8, in <module>
    from dynaconf.vendor.dotenv import cli as dotenv_cli
  File "/usr/local/lib/python3.8/site-packages/dynaconf/vendor/dotenv/cli.py", line 16, in <module>
    @click.option('-f','--file',default=os.path.join(os.getcwd(),'.env'),type=click.Path(exists=_A),help='Location of the .env file, defaults to .env file in current working directory.')
FileNotFoundError: [Errno 2] No such file or directory
Database migrated!
ready
Database migrated!
ready
```

**Comment by praiskup** [comment]
Also:
```
[2023-01-10 09:42:18 +0000] [12692] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/worker.py", line 57, in run
    self.loop.run_until_complete(self._task)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/worker.py", line 70, in _run
    wsgi = await self.wsgi()
  File "/usr/local/lib/python3.8/site-packages/pulpcore/content/__init__.py", line 65, in server
    os.chdir(settings.WORKING_DIRECTORY)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/pulp/tmp'
```
