### ISSUE TITLE
Generic repository and remote listing is broken

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulpcore#3713]
**Version**
pulpcore<=3.23

`http /pulp/api/v3/repositories/` and `http /pulp/api/v3/remotes/` returns 500.

traceback:
```
pulp_1   | pulp [2406ecb89afb41aea2c9125aab7ec1b7]: 127.0.0.1 - admin [06/Apr/2023:20:59:15 +0000] "GET /pulp/api/v3/repositories/ HTTP/1.0" 500 145 "-" "HTTPie/3.2.1"
pulp_1   | pulp [997616a0923049af988195c542b3a6b2]: django.request:ERROR: Internal Server Error: /pulp/api/v3/remotes/
pulp_1   | Traceback (most recent call last):
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
pulp_1   |     response = get_response(request)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
pulp_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
pulp_1   |     return view_func(*args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
pulp_1   |     return self.dispatch(request, *args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
pulp_1   |     response = self.handle_exception(exc)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
pulp_1   |     self.raise_uncaught_exception(exc)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
pulp_1   |     raise exc
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
pulp_1   |     response = handler(request, *args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 43, in list
pulp_1   |     return self.get_paginated_response(serializer.data)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
pulp_1   |     ret = super().data
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
pulp_1   |     self._data = self.to_representation(self.instance)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
pulp_1   |     return [
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
pulp_1   |     self.child.to_representation(item) for item in iterable
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
pulp_1   |     ret[field.field_name] = field.to_representation(attribute)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/relations.py", line 401, in to_representation
pulp_1   |     url = self.get_url(value, self.view_name, request, format)
pulp_1   |   File "/src/pulpcore/pulpcore/app/serializers/base.py", line 120, in get_url
pulp_1   |     view_name = self._view_name(obj)
pulp_1   |   File "/src/pulpcore/pulpcore/app/serializers/base.py", line 116, in _view_name
pulp_1   |     return get_view_name_for_model(obj, "detail")
pulp_1   |   File "/src/pulpcore/pulpcore/app/util.py", line 180, in get_view_name_for_model
pulp_1   |     raise LookupError("view not found")
pulp_1   | LookupError: view not found
```

**Comment by gerrod3** [comment]
Closing as not broken. My machine was in an inconsistent state since I created base `Repository` and `Remote` objects  in the DB with no plugin type.
