### ISSUE TITLE
Upstream Pulp replicate command traceback with DOMAIN_ENABLED=True

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#4119]
The replicate operation returns a 500 error when DOMAIN_ENABLED=True

```
bc45f6dcabec pulp [4b21bac6-dd0a-4105-b885-06b5f306baee]: 127.0.0.1 - admin [24/Jul/2023:16:03:54 +0000] "POST /pulp/a4c4beac-3eb9-47b3-9778-a9cb3c9fa18e/api/
v3/upstream-pulps/ HTTP/1.0" 201 539 "-" "api/test_replication.py::test_replication"
bc45f6dcabec pulp [4b21bac6-dd0a-4105-b885-06b5f306baee]: django.request:ERROR: Internal Server Error: /pulp/a4c4beac-3eb9-47b3-9778-a9cb3c9fa18e/api/v3/upstr
eam-pulps/018988a4-93b8-7e56-b5e8-de21862080de/replicate/
bc45f6dcabec Traceback (most recent call last):
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 416, in __getattr__
bc45f6dcabec     return getattr(self._request, attr)
bc45f6dcabec AttributeError: 'WSGIRequest' object has no attribute 'domain'
bc45f6dcabec
bc45f6dcabec During handling of the above exception, another exception occurred:
bc45f6dcabec
bc45f6dcabec Traceback (most recent call last):
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
bc45f6dcabec     response = get_response(request)
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
bc45f6dcabec     response = wrapped_callback(request, *callback_args, **callback_kwargs)
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
bc45f6dcabec     return view_func(*args, **kwargs)
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
bc45f6dcabec     return self.dispatch(request, *args, **kwargs)
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
bc45f6dcabec     response = self.handle_exception(exc)
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
bc45f6dcabec     self.raise_uncaught_exception(exc)
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
bc45f6dcabec     raise exc
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
bc45f6dcabec     response = handler(request, *args, **kwargs)
bc45f6dcabec   File "/src/pulpcore/pulpcore/app/viewsets/replica.py", line 49, in replicate
bc45f6dcabec     uri = f"/{request.domain.name}{uri}"
bc45f6dcabec   File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 418, in __getattr__
bc45f6dcabec     return self.__getattribute__(attr)
bc45f6dcabec AttributeError: 'Request' object has no attribute 'domain'
bc45f6dcabec pulp [4b21bac6-dd0a-4105-b885-06b5f306baee]: 127.0.0.1 - admin [24/Jul/2023:16:03:54 +0000] "POST /pulp/a4c4beac-3eb9-47b3-9778-a9cb3c9fa18e/api/v3/upstream-pulps/018988a4-93b8-7e56-b5e8-de21862080de/replicate/ HTTP/1.0" 500 145 "-" "api/test_replication.py::test_replication"
```

**Comment by ipanova** [comment]
any version we want to backport this to?
