### ISSUE TITLE
artifact re-upload triggers attributeerror on request.pulp_domain

### ISSUE THREAD

**Issue by jctanner** [pulp/pulpcore#4862]
**Version**
main branch and 3.28 and probably others.

**Describe the bug**
Upon re-uploading an artifact that triggers an IntegrityError, the code attempts to find the original artifact via the sha256 and the request's domain. However, on a system without domains enabled, the request object does NOT have a "domain" property.

**To Reproduce**
Re-upload the same collection artifact twice in galaxy_ng's master branch.

**Expected behavior**
Alter the artifact lookup kwargs to not include domain OR do a getattr(request, 'domain') or something to default to None.

**Additional context**

https://github.com/pulp/pulpcore/blame/3.28/pulpcore/plugin/viewsets/content.py#L111-L113
https://github.com/pulp/pulpcore/blame/main/pulpcore/plugin/viewsets/content.py#L112-L114

```
ci-standalone-pulp-1          | Traceback (most recent call last):
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
ci-standalone-pulp-1          |     response = get_response(request)
ci-standalone-pulp-1          |                ^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
ci-standalone-pulp-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
ci-standalone-pulp-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
ci-standalone-pulp-1          |     return view_func(*args, **kwargs)
ci-standalone-pulp-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
ci-standalone-pulp-1          |     return self.dispatch(request, *args, **kwargs)
ci-standalone-pulp-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
ci-standalone-pulp-1          |     response = self.handle_exception(exc)
ci-standalone-pulp-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
ci-standalone-pulp-1          |     self.raise_uncaught_exception(exc)
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
ci-standalone-pulp-1          |     raise exc
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
ci-standalone-pulp-1          |     response = handler(request, *args, **kwargs)
ci-standalone-pulp-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/src/galaxy_ng/galaxy_ng/app/api/v3/viewsets/collection.py", line 123, in create
ci-standalone-pulp-1          |     response = super(CollectionUploadViewSet, self).create(request, path)
ci-standalone-pulp-1          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/pulp_ansible/app/galaxy/v3/views.py", line 586, in create
ci-standalone-pulp-1          |     task_payload = self.init_content_data(serializer, request)
ci-standalone-pulp-1          |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/pulpcore/plugin/viewsets/content.py", line 112, in init_content_data
ci-standalone-pulp-1          |     sha256=artifact.sha256, pulp_domain=request.pulp_domain
ci-standalone-pulp-1          |                                         ^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          |   File "/usr/local/lib/python3.11/site-packages/rest_framework/request.py", line 418, in __getattr__
ci-standalone-pulp-1          |     return self.__getattribute__(attr)
ci-standalone-pulp-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ci-standalone-pulp-1          | AttributeError: 'Request' object has no attribute 'pulp_domain'
```

This is blocking galaxy_ng's CI right now because our re-upload artifact test fails in an unexpected way.

**Comment by jctanner** [comment]
Seems the assumption is that everyone needs to add the domain middleware to their plugin's settings.py.
