### ISSUE TITLE
[RFE?] Keep worker process running in case of db connection error

### ISSUE THREAD

**Issue by git-hyagi** [pulp/pulpcore#4998]
**Is your feature request related to a problem? Please describe.**
From time to time my Postgres instance restarts (not related to Pulp) which, in turn, causes a database connection error and pulpcore worker process exits (and pod restarts).

**Describe the solution you'd like**
Is there a way to handle these connection drops on pulpcore worker side? For example, the main process from pulpcore-api pods is a gunicorn app that forks children processes and whenever the connection to the database is lost, the api pods will throw exceptions but the main gunicorn process will keep running (only the forks will die), so this causes no pod restart. Is it possible to provide a similar behavior in pulpcore-worker pods so that the main process does not exit in case of database failure?  

**Additional context**
* We understand that the main problem is on the database side and the idea of this issue is just a "workaround".
* If we manage to find a way to keep the process running (and not restart the pod) will it handle/ensure the reconnection to the database?

**Comment by A1994SC** [comment]
The following is the error that happens when the postgres pod restarts

```text
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-worker", line 8, in <module>
    sys.exit(worker())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/entrypoint.py", line 43, in worker
    PulpcoreWorker().run(burst=burst)
  File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/worker.py", line 372, in run
    self.sleep()
  File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/worker.py", line 278, in sleep
    connection.connection.execute("SELECT 1")
  File "/usr/local/lib/python3.8/site-packages/psycopg/connection.py", line 896, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: consuming input failed: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by dkliban** [comment]
The restart behavior is helpful in identifying that there is a problem. Closing issue.
