### ISSUE TITLE
NotImplementedError: This backend doesn't support absolute paths (redhat repository)

### ISSUE THREAD

**Issue by orelops95** [pulp/pulpcore#5254]
**Version**
pulpcore: **v3.39.2**
Katello: **v4.11.1-1**
Os: Rocky **8.9**
s3_backend: **Scality**

**Describe the bug**
I have a problem with redhat repositories only, when a linux client wants to do a "yum update", I have an error 500 in the pulp-content logs:

```Apr 15 11:51:36 app01-alh pulpcore-content[48429]: [2024-04-15 09:51:36 +0000] [48429] [ERROR] Error handling request
Apr 15 11:51:36 app01-alh pulpcore-content[48429]: Traceback (most recent call last):
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib64/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     resp = await request_handler(request)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib64/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     resp = await handler(request)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:            ^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib64/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     return await handler(request)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:            ^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib/python3.11/site-packages/pulpcore/content/authentication.py", line 48, in authenticate
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     return await handler(request)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:            ^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib/python3.11/site-packages/pulpcore/cache/cache.py", line 339, in cached_function
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     response = await self.make_entry(
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:                ^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib/python3.11/site-packages/pulpcore/cache/cache.py", line 378, in make_entry
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     response = await handler(*args, **kwargs)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib/python3.11/site-packages/pulpcore/content/handler.py", line 249, in stream_content
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     return await self._match_and_stream(path, request)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib/python3.11/site-packages/pulpcore/content/handler.py", line 610, in _match_and_stream
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     return await self._serve_content_artifact(ca, headers, request)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:            
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib/python3.11/site-packages/pulpcore/content/handler.py", line 916, in _serve_content_artifact
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     path = storage.path(artifact_name)
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:   File "/usr/lib/python3.11/site-packages/django/core/files/storage/base.py", line 121, in path
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:     raise NotImplementedError("This backend doesn't support absolute paths.")
Apr 15 11:51:36 app01-alh pulpcore-content[48429]: NotImplementedError: This backend doesn't support absolute paths.
Apr 15 11:51:36 app01-alh pulpcore-content[48429]:  [15/Apr/2024:09:51:36 +0000] "GET /pulp/content/Default_Organization/Library/content/dist/rhel9/9/x86_64/baseos/os/repodata/repomd.xml HTTP/1.1" 500 245

````

Config S3 on pulp: 
```
AWS_S3_ENDPOINT_URL: "https://s3.domain.com"
AWS_S3_USE_SSL: True
AWS_ACCESS_KEY_ID = 'XXXXXXXXXXXXXXXXXX'
AWS_SECRET_ACCESS_KEY = 'XXXXXXXXXX'
AWS_STORAGE_BUCKET_NAME = 'pulp'
S3_USE_SIGV4 = True
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "virtual"
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_ROOT = ''
```
the following tasks work correctly:

- sync
- publish

with other repositories outside redhat I have no problem. 

Any ideas ?

**Comment by gerrod3** [comment]
@orelops95 Can you see what the output of `pulp domain show --name default`? If it returns a 500 error or you see in the response that the `storage_class` is not `storages.backends.s3boto3.S3Boto3Storage` then can you try running `pulpcore-manager migrate`. Afterwards can you see if the issue persists?

**Comment by ggainey** [comment]
> @gerrod3 pulpcore-manager migrate fixed my problem ! but I still have a problem on my client
> [depted URL that may have included sensitive info]
> but all my certificates are okGenerally this means that the self-signed cert's CA isn't in the client's trust-db. The process for getting it there varies with the client

There's a self-signed cert presented by Pulp that isn't in your client's trust-db. You'll want to do some searching on how to get it there (I def don't know the right incantation off the top of my head :) ) for you specific distro!

(NOTE: I deleted your comment because it looked like it might have some creds in it. Def check URLs w/ care when pasting!  If they were stale/test data, then no harm done)

**Comment by orelops95** [comment]
my bad ! bad copy paste ! 

_There's a self-signed cert presented by Pulp that isn't in your client's trust-db. You'll want to do some searching on how to get it there (I def don't know the right incantation off the top of my head :) ) for you specific distro!_

I put the certificates in the /etc/pki/ca-trust/source/anchors/ and trust extract-compat , but the problem seems the same.

**Comment by orelops95** [comment]
@gerrod3 @ggainey 
I just checked my config, but I don't see any errors, if I disable ssl verification everything works fine, but I don't understand why I have an error on the s3 certificate on my client.

client os: rhel9.3

```
- Curl error (60): SSL peer certificate or SSH remote key was not OK for https://s3.mydomain.com/pulp/artifact/c1/

**Comment by ggainey** [comment]
Hrm. Are we even getting as far as the S3 cert? Or are we hung up at talking to pulp itself?

Can you show us (sans auth-tokens :) ) the exact curl-cmd you're using and the full output?

**Comment by orelops95** [comment]
@ggainey, 

The curl command it's ok ! 

check ssl certificate are ok

```
SSL certificate verify ok.
* TLSv1.2 (IN), TLS header, Unknown (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: openresty
< Date: Wed, 17 Apr 2024 13:43:24 GMT
< Content-Type: text/xml
< Content-Length: 4159
< Connection: keep-alive
< Accept-Ranges: bytes
< ETag: "1234567890"
< Last-Modified: Tue, 16 Apr 2024 08:21:33 GMT
< Cache-Control: no-cache
< Content-Disposition: attachment;filename=repomd.xml
< x-amz-id-2: XXXXXXXXXXXX
< x-amz-request-id: XXXXXXXXXXX
< Strict-Transport-Security: max-age=31536000; includeSubdomains ; preload; always

```
but when I run the yum command, it gives me a certificate error, yum/dnf does not use an alternative source to validate the certificate ?

**Comment by gerrod3** [comment]
I think this confirms that the problem is yum is not correctly set up with the ssl certs for your S3 storage. By default when using cloud storage Pulp will redirect the final request to the cloud and have it stream the artifact to your clients. By turning off redirect, Pulp becomes the one to stream the bits. This will reduce the performance of the content app, but if you can't figure out the cert issue then it may be the best alternative.

**Comment by ggainey** [comment]
Closing - looks like we've identified the problem-areas as not-pulp
