### ISSUE TITLE
renaming a domain results in error

### ISSUE THREAD

**Issue by jlsherrill** [pulp/pulpcore#6025]
**Version**
      "version": "3.67.0",

**Describe the bug**

Performing a patch request against a domain to rename it no longer works:

```
PATCH /api/pulp/default/api/v3/domains/01932ba9-c6d9-7425-bd61-d030fa9862c9/ HTTP/1.1
Host: localhost:8080
User-Agent: OpenAPI-Generator/b59d5a8be2d6a9584b32d696a45276486d3832127b8e3dae95843eb29436da38/go
Content-Length: 21
Accept: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Content-Type: application/json
Correlation-Id: f60ea5eb-7662-4eb4-b311-4632451e32e3
Accept-Encoding: gzip

{"name":"cs-redhat"}
```

```
Traceback (most recent call last):
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 94, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/app/viewsets/base.py", line 509, in partial_update
    return self.update(request, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/app/viewsets/domain.py", line 116, in update
    return super().update(request, pk, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/app/viewsets/base.py", line 492, in update
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/app/serializers/domain.py", line 470, in validate
    self._validate_storage_backend(storage_class, storage_settings)
  File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/app/serializers/domain.py", line 417, in _validate_storage_backend
    backend(**storage_settings)
TypeError: pulpcore.app.models.storage.FileSystem() argument after ** must be a mapping, not NoneType
```

**To Reproduce**

Create a domain using "pulpcore.app.models.storage.FileSystem"  storage.  I'm not sure if other storages also have this issue

Create and sync some content in the domain (not sure if this is required)

Try to rename the domain.

**Expected behavior**
should be able to be renamed

**Comment by dkliban** [comment]
I couldn't reproduce this upstream. Must be related to the patches I applied to our deployment.
